export const projects = [
  {
    title: 'Marketplace App',
    description: "A marketplace where creators can sell their digital content",
      image: '/images/rails-ecommerce.png',
      tags: ['Ruby on Rails', 'Tailwind UI', 'PostgresSQL', 'Redis'],
    source: 'https://github.com/RianNegreiros/rails_ecommerce',
    visit: 'https://ror-marketplace.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Lodging App',
    description:"A application for short-term rentals like Airbnb",
    image: '/images/lodging.png',
    tags: ['Ruby on Rails', 'Tailwind UI', 'PostgresSQL'],
    source: 'https://github.com/RianNegreiros/lodging_app',
    visit: 'https://lodging-app.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Rails social network',
    description: "A social network using Ruby on Rails",
      image: '/images/rails-social-network.png',
      tags: ['Ruby on Rails', 'Bootstrap', 'jQuery'],
    source: 'https://github.com/RianNegreiros/rails_social_network',
    visit: 'https://social-network-ror.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Instagram clone',
    description: "A instagram clone using Ruby on Rails",
    image: '/images/rails-instagram-clone.png',
    tags: ['Ruby on Rails', 'Redis', 'PostgresSQL'],
    source: 'https://github.com/RianNegreiros/rails-instagram-clone',
    visit: 'https://ror-instagram-clone.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Overtime',
    description: "Enterprise application to manage employees overtimes",
    image: '/images/overtime.png',
    tags: ['Ruby on Rails', 'Bootstrap'],
    source: 'https://github.com/RianNegreiros/overtime',
    visit: 'https://overtime-ror.herokuapp.com/',
    id: 4,
  },
  {
    title: 'Social network',
    description: "Full-Stack application to users share their activities, and follow activities from others",
    image: '/images/dotnet-react-social-network.png',
    tags: ['Reactjs', 'Typescript', '.NET Core', 'PostgreSQL'],
    source: 'https://github.com/RianNegreiros/dotnet-react-social-network',
    visit: 'https://dotnet-react-social-network.herokuapp.com/',
    id: 5,
  },
  {
    title: 'E-commerce Microservices',
    description: "E-commerce Microservices demo application deployed on Kubernetes",
    image: '/images/ecommerce-microservices.png',
    tags: ['.NET Core', 'Bootstrap', 'RabbitMQ'],
    source: 'https://github.com/RianNegreiros/EcommerceMicroservices',
    visit: 'https://dev.azure.com/riannegreiros/EcommerceMicroservices/_build',
    id: 6,
  },
];