export const projects = [
  {
    title: 'Marketplace App',
    description: "A marketplace where creators can sell their digital content",
      image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/rails-ecommerce.png?raw=true',
      tags: ['Ruby on Rails', 'Tailwind UI', 'PostgresSQL', 'Redis'],
    source: 'https://github.com/RianNegreiros/rails_ecommerce',
    visit: 'https://ror-marketplace.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Lodging App',
    description:"A application for short-term rentals like Airbnb",
    image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/lodging.png?raw=true',
    tags: ['Ruby on Rails', 'Tailwind UI', 'PostgresSQL'],
    source: 'https://github.com/RianNegreiros/lodging_app',
    visit: 'https://lodging-app.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Rails social network',
    description: "A social network using Ruby on Rails",
      image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/rails-social-network.png?raw=true',
      tags: ['Ruby on Rails', 'Bootstrap', 'jQuery'],
    source: 'https://github.com/RianNegreiros/rails_social_network',
    visit: 'https://social-network-ror.herokuapp.com/',
    id: 2,
  },
  {
    title: 'Instagram clone',
    description: "A instagram clone using Ruby on Rails",
    image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/rails-instagram-clone.png?raw=true',
    tags: ['Ruby on Rails', 'Redis', 'PostgresSQL'],
    source: 'https://github.com/RianNegreiros/rails-instagram-clone',
    visit: 'https://ror-instagram-clone.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Overtime',
    description: "Enterprise application to manage employees overtimes",
    image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/overtime.png?raw=true',
    tags: ['Ruby on Rails', 'Bootstrap'],
    source: 'https://github.com/RianNegreiros/overtime',
    visit: 'https://overtime-ror.herokuapp.com/',
    id: 4,
  },
  {
    title: 'Social network',
    description: "Full-Stack application to users share their activities, and follow activities from others",
    image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/dotnet-react-social-network.png?raw=true',
    tags: ['Reactjs', 'Typescript', '.NET Core', 'PostgreSQL'],
    source: 'https://github.com/RianNegreiros/dotnet-react-social-network',
    visit: 'https://dotnet-react-social-network.herokuapp.com/',
    id: 5,
  },
  {
    title: 'E-commerce Microservices',
    description: "E-commerce Microservices demo application deployed on Kubernetes",
    image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/ecommerce-microservices.png?raw=true',
    tags: ['.NET Core', 'Bootstrap', 'RabbitMQ'],
    source: 'https://github.com/RianNegreiros/EcommerceMicroservices',
    visit: 'https://dev.azure.com/riannegreiros/EcommerceMicroservices/_build',
    id: 6,
  },
  {
    title: 'Todo app',
    description: "Frontend Mentor - Todo app solution",
    image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/todo-list.png?raw=true',
    tags: ['ReactJs', 'SASS'],
    source: 'https://github.com/RianNegreiros/todo-app-main-frontend-mentor',
    visit: 'https://todo-app-main-frontend-mentor.vercel.app/',
    id: 7,
  },
  {
    title: 'IP Tracker',
    description: "Frontend Mentor - IP address tracker solution",
    image: 'https://github.com/RianNegreiros/portfolio/blob/main/public/images/ip-tracker.png?raw=true',
    tags: ['ReactJs', 'SASS', 'Axios'],
    source: 'https://github.com/RianNegreiros/ip-address-tracker-frontend-mentor',
    visit: 'https://ip-address-tracker-master-eight.vercel.app/',
    id: 7,
  },
];